indent = 2
margin = 80
always_for_in = true
remove_extra_newlines = true
short_to_long_function_def = true
long_to_short_function_def = true
always_use_return = true
format_docstrings = true
conditional_to_if = true
