# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.0"
manifest_format = "2.0"
project_hash = "6283fef0c59054ede43e8d7d17ebd77796f33749"

[[deps.Varis]]
path = "."
uuid = "3415f407-0286-4f55-86f3-e77e3bac4fc9"
version = "1.0.0-DEV"
